// generated by stringer -type=SVType; DO NOT EDIT

package vcf

import "fmt"

const _SVType_name = "DeletionDuplicationInsertionInversionCopyNumberVariationTandemDuplicationDeletionMobileElementInsertionMobileElementBreakend"

var _SVType_index = [...]uint8{0, 8, 19, 28, 37, 56, 73, 94, 116, 124}

func (i SVType) String() string {
	if i < 0 || i >= SVType(len(_SVType_index)-1) {
		return fmt.Sprintf("SVType(%d)", i)
	}
	return _SVType_name[_SVType_index[i]:_SVType_index[i+1]]
}
